### ISSUE TITLE
LED Driver chip

### ISSUE THREAD

**Issue by Meshme** [fmalpartida/laser-driver#1]

**Comment by troth530** [comment]
I have the same question.  Thank you.

**Comment by fmalpartida** [comment]
And the question is?

**Comment by troth530** [comment]
Sorry for being vague.  What is the 8 pin driver chip?  Thank you.

**Comment by JRodrigoTech** [comment]
The repository is perfect, you just have to look a little bit the ploject 

https://github.com/fmalpartida/laser-driver/blob/18474f128884661c4b68944d75d2ce46efa0ffbf/laserDriver.sch#L181
